- hosts: webservers
  become: true
  become_user: root
  tasks:
  - name: install tomcat
    yum: name=tomcat state=present
  - name: start tomcat
    service: name=tomcat state=started
  - name: deploy war file
    get_url:
     url=https://github.com/imanojk4/myansibl/blob/main/addressbook%20.war
     dest=/usr/share/tomcat/webapps
    notify: restart tomcat
  handlers:
   - name: restart tomcat
     service: name=tomcat state=restarted
  
  
  
